### ISSUE TITLE
Is it possible to make it work with magicuser theme ?

### ISSUE THREAD

**Issue by munish259272** [RavenHogWarts/obsidian-custom-icons#20]
I was having problem with magicuser theme and it works fine now with manual CSS file creation with some changes as suggested here by creator of magicuser here https://github.com/drbap/magicuser-theme-for-obsidian/issues/69

**Comment by munish259272** [comment]
It is working now with custom css

```css
.nav-file-title[data-path] .nav-file-title-content::before {
  mask-image: none;
  -webkit-mask-image: none;
}
```
